server:
  port: 10010 #?????????
eureka:
  instance:
    hostname: 43.143.173.212 #??????IP??
  client:
    registerWithEureka: false #?????????????
    fetchRegistry: false #??????
    serviceUrl: #???????????????????????
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://114.115.213.111:${server.port}/eureka/

