package com.jianyi.jianyiblog.entity.dto;

public class CategoryDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
}
