#eureka:
#  client:
#    serviceUrl: #?????????
#      defaultZone: http://43.143.173.212:10010/eureka/
#  instance:
#    instance-id: 114.115.213.111:${spring.application.name}:${server.port}
#    hostname: 114.115.213.111
#    ip-address: true
eureka:
  client:
    serviceUrl: #?????????
      defaultZone: http://127.0.0.1:10010/eureka/
  instance:
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}
    hostname: 127.0.0.1
    ip-address: true
spring:
  #rabbitmq??
  rabbitmq:
    username: admin
    password: admin
    addresses: 114.115.213.111:5672
  application:
    name: jianyi-rabbitmq
server:
  port: 10011
