package com.jianyi.jianyiblog.entity;

import java.util.Date;

public class BlogLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.label_id
     *
     * @mbg.generated
     */
    private Integer labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.label_name
     *
     * @mbg.generated
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.label_alias
     *
     * @mbg.generated
     */
    private String labelAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.label_remark
     *
     * @mbg.generated
     */
    private String labelRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.CREATED_TIME
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.UPDATED_BY
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.UPDATED_TIME
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.label_id
     *
     * @return the value of blog_label.label_id
     *
     * @mbg.generated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.label_id
     *
     * @param labelId the value for blog_label.label_id
     *
     * @mbg.generated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.label_name
     *
     * @return the value of blog_label.label_name
     *
     * @mbg.generated
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.label_name
     *
     * @param labelName the value for blog_label.label_name
     *
     * @mbg.generated
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.label_alias
     *
     * @return the value of blog_label.label_alias
     *
     * @mbg.generated
     */
    public String getLabelAlias() {
        return labelAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.label_alias
     *
     * @param labelAlias the value for blog_label.label_alias
     *
     * @mbg.generated
     */
    public void setLabelAlias(String labelAlias) {
        this.labelAlias = labelAlias == null ? null : labelAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.label_remark
     *
     * @return the value of blog_label.label_remark
     *
     * @mbg.generated
     */
    public String getLabelRemark() {
        return labelRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.label_remark
     *
     * @param labelRemark the value for blog_label.label_remark
     *
     * @mbg.generated
     */
    public void setLabelRemark(String labelRemark) {
        this.labelRemark = labelRemark == null ? null : labelRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.CREATED_BY
     *
     * @return the value of blog_label.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.CREATED_BY
     *
     * @param createdBy the value for blog_label.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.CREATED_TIME
     *
     * @return the value of blog_label.CREATED_TIME
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.CREATED_TIME
     *
     * @param createdTime the value for blog_label.CREATED_TIME
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.UPDATED_BY
     *
     * @return the value of blog_label.UPDATED_BY
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.UPDATED_BY
     *
     * @param updatedBy the value for blog_label.UPDATED_BY
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.UPDATED_TIME
     *
     * @return the value of blog_label.UPDATED_TIME
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.UPDATED_TIME
     *
     * @param updatedTime the value for blog_label.UPDATED_TIME
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", labelId=").append(labelId);
        sb.append(", labelName=").append(labelName);
        sb.append(", labelAlias=").append(labelAlias);
        sb.append(", labelRemark=").append(labelRemark);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}