package com.jianyi.jianyiblog.entity;

public class BlogBlogCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog_category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog_category.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog_category.cate_id
     *
     * @mbg.generated
     */
    private Integer cateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog_category.id
     *
     * @return the value of blog_blog_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog_category.id
     *
     * @param id the value for blog_blog_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog_category.blog_id
     *
     * @return the value of blog_blog_category.blog_id
     *
     * @mbg.generated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog_category.blog_id
     *
     * @param blogId the value for blog_blog_category.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog_category.cate_id
     *
     * @return the value of blog_blog_category.cate_id
     *
     * @mbg.generated
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog_category.cate_id
     *
     * @param cateId the value for blog_blog_category.cate_id
     *
     * @mbg.generated
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_blog_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", blogId=").append(blogId);
        sb.append(", cateId=").append(cateId);
        sb.append("]");
        return sb.toString();
    }
}