package com.jianyi.jianyiblog.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;
import java.util.List;

/**
 * 博客文章类
 */
public class    Blog {
    /**
     * 主键
     */
    private Long blogId;

    /**
     *标题
     */
    private String blogTitle;

    /**
     *博文内容
     */
    private String blogContent;

    /**
     *点赞数
     */
    private Long blogLike;

    /**
     *评论数
     */
    private Long blogComments;

    /**
     *浏览量
     */
    private Long blogBrowsing;

    /**
     *文章摘要
     */
    private String blogAbstract;

    /**
     *博文封面
     */
    private String blogCover;

    /**
     *创建人
     */
    private String createdBy;

    /**
     *创建时间
     */
    private String createdTime;

    /**
     *修改人
     */
    private String updatedBy;

    /**修改时间
     */
    private String updatedTime;

    private  String cates;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<BlogCategory> checkCateList;

    public List<BlogCategory> getCheckCateList() {
        return checkCateList;
    }

    public String getCates() {
        return cates;
    }

    public void setCates(String cates) {
        this.cates = cates;
    }

    public void setCheckCateList(List<BlogCategory> checkCateList) {
        this.checkCateList = checkCateList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_id
     *
     * @return the value of blog.blog_id
     *
     * @mbg.generated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_id
     *
     * @param blogId the value for blog.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_title
     *
     * @return the value of blog.blog_title
     *
     * @mbg.generated
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_title
     *
     * @param blogTitle the value for blog.blog_title
     *
     * @mbg.generated
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_content
     *
     * @return the value of blog.blog_content
     *
     * @mbg.generated
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_content
     *
     * @param blogContent the value for blog.blog_content
     *
     * @mbg.generated
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_like
     *
     * @return the value of blog.blog_like
     *
     * @mbg.generated
     */
    public Long getBlogLike() {
        return blogLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_like
     *
     * @param blogLike the value for blog.blog_like
     *
     * @mbg.generated
     */
    public void setBlogLike(Long blogLike) {
        this.blogLike = blogLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_comments
     *
     * @return the value of blog.blog_comments
     *
     * @mbg.generated
     */
    public Long getBlogComments() {
        return blogComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_comments
     *
     * @param blogComments the value for blog.blog_comments
     *
     * @mbg.generated
     */
    public void setBlogComments(Long blogComments) {
        this.blogComments = blogComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_browsing
     *
     * @return the value of blog.blog_browsing
     *
     * @mbg.generated
     */
    public Long getBlogBrowsing() {
        return blogBrowsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_browsing
     *
     * @param blogBrowsing the value for blog.blog_browsing
     *
     * @mbg.generated
     */
    public void setBlogBrowsing(Long blogBrowsing) {
        this.blogBrowsing = blogBrowsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_abstract
     *
     * @return the value of blog.blog_abstract
     *
     * @mbg.generated
     */
    public String getBlogAbstract() {
        return blogAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_abstract
     *
     * @param blogAbstract the value for blog.blog_abstract
     *
     * @mbg.generated
     */
    public void setBlogAbstract(String blogAbstract) {
        this.blogAbstract = blogAbstract == null ? null : blogAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_cover
     *
     * @return the value of blog.blog_cover
     *
     * @mbg.generated
     */
    public String getBlogCover() {
        return blogCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_cover
     *
     * @param blogCover the value for blog.blog_cover
     *
     * @mbg.generated
     */
    public void setBlogCover(String blogCover) {
        this.blogCover = blogCover == null ? null : blogCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.CREATED_BY
     *
     * @return the value of blog.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.CREATED_BY
     *
     * @param createdBy the value for blog.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.UPDATED_BY
     *
     * @return the value of blog.UPDATED_BY
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.UPDATED_BY
     *
     * @param updatedBy the value for blog.UPDATED_BY
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }


    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", blogId=").append(blogId);
        sb.append(", blogTitle=").append(blogTitle);
        sb.append(", blogContent=").append(blogContent);
        sb.append(", blogLike=").append(blogLike);
        sb.append(", blogComments=").append(blogComments);
        sb.append(", blogBrowsing=").append(blogBrowsing);
        sb.append(", blogAbstract=").append(blogAbstract);
        sb.append(", blogCover=").append(blogCover);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}