package com.jianyi.jianyiblog.entity;

import java.util.Date;

/**
 * 博客类别
 *
 */
public class BlogCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.category_pid
     *
     * @mbg.generated
     */
    private Integer categoryPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.category_remark
     *
     * @mbg.generated
     */
    private String categoryRemark;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.CREATED_TIME
     *
     * @mbg.generated
     */
    private String createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.UPDATED_BY
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category.UPDATED_TIME
     *
     * @mbg.generated
     */
    private String updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category.category_id
     *
     * @return the value of blog_category.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category.category_id
     *
     * @param categoryId the value for blog_category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category.category_name
     *
     * @return the value of blog_category.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category.category_name
     *
     * @param categoryName the value for blog_category.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category.category_pid
     *
     * @return the value of blog_category.category_pid
     *
     * @mbg.generated
     */
    public Integer getCategoryPid() {
        return categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category.category_pid
     *
     * @param categoryPid the value for blog_category.category_pid
     *
     * @mbg.generated
     */
    public void setCategoryPid(Integer categoryPid) {
        this.categoryPid = categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category.category_remark
     *
     * @return the value of blog_category.category_remark
     *
     * @mbg.generated
     */
    public String getCategoryRemark() {
        return categoryRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category.category_remark
     *
     * @param categoryRemark the value for blog_category.category_remark
     *
     * @mbg.generated
     */
    public void setCategoryRemark(String categoryRemark) {
        this.categoryRemark = categoryRemark == null ? null : categoryRemark.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category.CREATED_BY
     *
     * @return the value of blog_category.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category.CREATED_BY
     *
     * @param createdBy the value for blog_category.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category.UPDATED_BY
     *
     * @return the value of blog_category.UPDATED_BY
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category.UPDATED_BY
     *
     * @param updatedBy the value for blog_category.UPDATED_BY
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", categoryPid=").append(categoryPid);
        sb.append(", categoryRemark=").append(categoryRemark);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}