package com.jianyi.jianyiblog.entity;

public class BlogLook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_look.look_id
     *
     * @mbg.generated
     */
    private Long lookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_look.look_uid
     *
     * @mbg.generated
     */
    private Long lookUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_look.blog_id
     *
     * @mbg.generated
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_look.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    public BlogLook(Long lookUid, Long blogId,String createTime) {
        this.lookUid = lookUid;
        this.blogId = blogId;
        this.createTime = createTime;
    }

    public BlogLook() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_look.look_id
     *
     * @return the value of blog_look.look_id
     *
     * @mbg.generated
     */
    public Long getLookId() {
        return lookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_look.look_id
     *
     * @param lookId the value for blog_look.look_id
     *
     * @mbg.generated
     */
    public void setLookId(Long lookId) {
        this.lookId = lookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_look.look_uid
     *
     * @return the value of blog_look.look_uid
     *
     * @mbg.generated
     */
    public Long getLookUid() {
        return lookUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_look.look_uid
     *
     * @param lookUid the value for blog_look.look_uid
     *
     * @mbg.generated
     */
    public void setLookUid(Long lookUid) {
        this.lookUid = lookUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_look.blog_id
     *
     * @return the value of blog_look.blog_id
     *
     * @mbg.generated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_look.blog_id
     *
     * @param blogId the value for blog_look.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_look.create_time
     *
     * @return the value of blog_look.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_look.create_time
     *
     * @param createTime the value for blog_look.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lookId=").append(lookId);
        sb.append(", lookUid=").append(lookUid);
        sb.append(", blogId=").append(blogId);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}