package com.jianyi.jianyiblog.entity;

import com.jianyi.jianyiblog.entity.dto.CommentTree;

import java.util.Date;

public class BlogComment extends CommentTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_uid
     *
     * @mbg.generated
     */
    private Integer commentUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_text
     *
     * @mbg.generated
     */
    private String commentText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_pid
     *
     * @mbg.generated
     */
    private Integer commentPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.blog_id
     *
     * @mbg.generated
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.admin_comment
     *
     * @mbg.generated
     */
    private Integer adminComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.start_num
     *
     * @mbg.generated
     */
    private Integer startNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.CREATED_TIME
     *
     * @mbg.generated
     */
    private String createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.UPDATED_BY
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.UPDATED_TIME
     *
     * @mbg.generated
     */
    private String updatedTime;

    //回复名称

    private String replyName;

    public String getReplyName() {
        return replyName;
    }

    public void setReplyName(String replyName) {
        this.replyName = replyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_id
     *
     * @return the value of blog_comment.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_id
     *
     * @param commentId the value for blog_comment.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_uid
     *
     * @return the value of blog_comment.comment_uid
     *
     * @mbg.generated
     */
    public Integer getCommentUid() {
        return commentUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_uid
     *
     * @param commentUid the value for blog_comment.comment_uid
     *
     * @mbg.generated
     */
    public void setCommentUid(Integer commentUid) {
        this.commentUid = commentUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_text
     *
     * @return the value of blog_comment.comment_text
     *
     * @mbg.generated
     */
    public String getCommentText() {
        return commentText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_text
     *
     * @param commentText the value for blog_comment.comment_text
     *
     * @mbg.generated
     */
    public void setCommentText(String commentText) {
        this.commentText = commentText == null ? null : commentText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_pid
     *
     * @return the value of blog_comment.comment_pid
     *
     * @mbg.generated
     */
    public Integer getCommentPid() {
        return commentPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_pid
     *
     * @param commentPid the value for blog_comment.comment_pid
     *
     * @mbg.generated
     */
    public void setCommentPid(Integer commentPid) {
        this.commentPid = commentPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.blog_id
     *
     * @return the value of blog_comment.blog_id
     *
     * @mbg.generated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.blog_id
     *
     * @param blogId the value for blog_comment.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.admin_comment
     *
     * @return the value of blog_comment.admin_comment
     *
     * @mbg.generated
     */
    public Integer getAdminComment() {
        return adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.admin_comment
     *
     * @param adminComment the value for blog_comment.admin_comment
     *
     * @mbg.generated
     */
    public void setAdminComment(Integer adminComment) {
        this.adminComment = adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.start_num
     *
     * @return the value of blog_comment.start_num
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.start_num
     *
     * @param startNum the value for blog_comment.start_num
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.CREATED_BY
     *
     * @return the value of blog_comment.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.CREATED_BY
     *
     * @param createdBy the value for blog_comment.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.CREATED_TIME
     *
     * @return the value of blog_comment.CREATED_TIME
     *
     * @mbg.generated
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.CREATED_TIME
     *
     * @param createdTime the value for blog_comment.CREATED_TIME
     *
     * @mbg.generated
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.UPDATED_BY
     *
     * @return the value of blog_comment.UPDATED_BY
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.UPDATED_BY
     *
     * @param updatedBy the value for blog_comment.UPDATED_BY
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.UPDATED_TIME
     *
     * @return the value of blog_comment.UPDATED_TIME
     *
     * @mbg.generated
     */
    public String getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.UPDATED_TIME
     *
     * @param updatedTime the value for blog_comment.UPDATED_TIME
     *
     * @mbg.generated
     */
    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", commentUid=").append(commentUid);
        sb.append(", commentText=").append(commentText);
        sb.append(", commentPid=").append(commentPid);
        sb.append(", blogId=").append(blogId);
        sb.append(", adminComment=").append(adminComment);
        sb.append(", startNum=").append(startNum);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}