package com.jianyi.jianyiblog.entity;

public class CollectionGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_group.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_group.group_pid
     *
     * @mbg.generated
     */
    private Long groupPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_group.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_group.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_group.group_remark
     *
     * @mbg.generated
     */
    private String groupRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_group.group_id
     *
     * @return the value of collection_group.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_group.group_id
     *
     * @param groupId the value for collection_group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_group.group_name
     *
     * @return the value of collection_group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_group.group_name
     *
     * @param groupName the value for collection_group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_group.group_pid
     *
     * @return the value of collection_group.group_pid
     *
     * @mbg.generated
     */
    public Long getGroupPid() {
        return groupPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_group.group_pid
     *
     * @param groupPid the value for collection_group.group_pid
     *
     * @mbg.generated
     */
    public void setGroupPid(Long groupPid) {
        this.groupPid = groupPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_group.create_time
     *
     * @return the value of collection_group.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_group.create_time
     *
     * @param createTime the value for collection_group.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_group.user_id
     *
     * @return the value of collection_group.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_group.user_id
     *
     * @param userId the value for collection_group.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_group.group_remark
     *
     * @return the value of collection_group.group_remark
     *
     * @mbg.generated
     */
    public String getGroupRemark() {
        return groupRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_group.group_remark
     *
     * @param groupRemark the value for collection_group.group_remark
     *
     * @mbg.generated
     */
    public void setGroupRemark(String groupRemark) {
        this.groupRemark = groupRemark == null ? null : groupRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", groupName=").append(groupName);
        sb.append(", groupPid=").append(groupPid);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append(", groupRemark=").append(groupRemark);
        sb.append("]");
        return sb.toString();
    }
}