package com.jianyi.jianyiblog.mapper;

import com.jianyi.jianyiblog.entity.BlogLook;
import com.jianyi.jianyiblog.entity.BlogLookExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BlogLookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    long countByExample(BlogLookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int deleteByExample(BlogLookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long lookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int insert(BlogLook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int insertSelective(BlogLook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    List<BlogLook> selectByExample(BlogLookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    BlogLook selectByPrimaryKey(Long lookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlogLook record, @Param("example") BlogLookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlogLook record, @Param("example") BlogLookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogLook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_look
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogLook record);
}