package com.jianyi.jianyiblog.mapper;

import com.jianyi.jianyiblog.entity.BlogCollection;
import com.jianyi.jianyiblog.entity.BlogCollectionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BlogCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    long countByExample(BlogCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int deleteByExample(BlogCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int insert(BlogCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int insertSelective(BlogCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    List<BlogCollection> selectByExample(BlogCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    BlogCollection selectByPrimaryKey(Long collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlogCollection record, @Param("example") BlogCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlogCollection record, @Param("example") BlogCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collection
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogCollection record);
}