package com.jianyi.jianyiblog.mapper;

import com.jianyi.jianyiblog.entity.BlogCategory;
import com.jianyi.jianyiblog.entity.BlogCategoryExample;
import java.util.List;

import com.jianyi.jianyiblog.entity.dto.BlogDto;
import com.jianyi.jianyiblog.entity.dto.CategoryDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    long countByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int deleteByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int insert(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int insertSelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    List<BlogCategory> selectByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    BlogCategory selectByPrimaryKey(Integer categoryId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    BlogCategory selectByPrimaryKeyName(BlogCategory blogCategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlogCategory record, @Param("example") BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlogCategory record, @Param("example") BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogCategory record);

    /**
     * 根据文章绑定的标签获取标签上级集合
     * @param family
     * @return
     */
    List<Long> selectFamilyFromPids(String family);

    /**
     * 根据标签id组获取标签集合
     */
    List<CategoryDto> selectByIds(String ids);
}