package com.jianyi.jianyiblog.mapper;

import com.jianyi.jianyiblog.entity.BlogLabel;
import com.jianyi.jianyiblog.entity.BlogLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    long countByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int deleteByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int insert(BlogLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int insertSelective(BlogLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    List<BlogLabel> selectByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    BlogLabel selectByPrimaryKey(Integer labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlogLabel record, @Param("example") BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlogLabel record, @Param("example") BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogLabel record);
}