package com.jianyi.jianyiblog.mapper;

import com.jianyi.jianyiblog.entity.CollectionGroup;
import com.jianyi.jianyiblog.entity.CollectionGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectionGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    long countByExample(CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int deleteByExample(CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int insert(CollectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int insertSelective(CollectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    List<CollectionGroup> selectByExample(CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    CollectionGroup selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CollectionGroup record, @Param("example") CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CollectionGroup record, @Param("example") CollectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CollectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CollectionGroup record);
}